name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # PAC-MAN Animation
      - uses: Platane/PAC-MAN@master
        id: PAC-MAN-gif
        with:
          github_user_name: sarahmonteiroanjos
          svg_out_path: dist/github-contribution-grid-PAC-MAN.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
